/**
 * Part types used to pick an illustrative photo for a product that has no photo of its own.
 * A type is recognised from the category slug and words of the Portuguese product name
 * (the catalogue's canonical name). Order matters: the first match wins.
 *
 * `search` (English) and `terms` (pt/es/fr/de) are used to look for freely licensed photos (scripts/images).
 */
export interface PartType {
  key: string
  /** Name shown to customers (categories page). */
  label: Record<'pt' | 'es' | 'en' | 'fr' | 'de' | 'it', string>
  category: string
  /** Matched against the accent-free, lower-case product name. */
  match: RegExp
  search: string
  /** Same search in the other languages of the shop (Commons has many captions in pt/es/fr/de). */
  terms?: Partial<Record<'pt' | 'es' | 'fr' | 'de', string>>
  /** Wikimedia Commons categories with photos of this part (curated; more precise than free search). */
  commons?: string[]
  /** Closest other type whose photo to use while this one has none (before any photo of the category). */
  similar?: string
}

export const PART_TYPES: PartType[] = [
  // travagem
  { key: 'brake-pads', label: { pt: 'Pastilhas de travão', es: 'Pastillas de freno', en: 'Brake pads', fr: 'Plaquettes de frein', de: 'Bremsbeläge', it: 'Pastiglie freno' }, category: 'travagem', match: /pastilha/, search: 'brake pads', terms: { pt: 'pastilhas de travão', es: 'pastillas de freno', fr: 'plaquettes de frein', de: 'Bremsbeläge' }, commons: ['Brake pads'] },
  { key: 'brake-disc', label: { pt: 'Discos de travão', es: 'Discos de freno', en: 'Brake discs', fr: 'Disques de frein', de: 'Bremsscheiben', it: 'Dischi freno' }, category: 'travagem', match: /disco/, search: 'brake disc rotor', terms: { pt: 'disco de travão', es: 'disco de freno', fr: 'disque de frein', de: 'Bremsscheibe' }, commons: ['Brake discs', 'Automobile disk brakes'] },
  { key: 'brake-caliper', label: { pt: 'Pinças de travão', es: 'Pinzas de freno', en: 'Brake calipers', fr: 'Étriers de frein', de: 'Bremssättel', it: 'Pinze freno' }, category: 'travagem', match: /pinca/, search: 'brake caliper', terms: { pt: 'pinça de travão', es: 'pinza de freno', fr: 'étrier de frein', de: 'Bremssattel' }, commons: ['Brake calipers'] },
  // filtros
  { key: 'oil-filter', label: { pt: 'Filtros de óleo', es: 'Filtros de aceite', en: 'Oil filters', fr: 'Filtres à huile', de: 'Ölfilter', it: 'Filtri olio' }, category: 'filtros', match: /filtro de oleo/, search: 'oil filter', terms: { pt: 'filtro de óleo', es: 'filtro de aceite', fr: 'filtre à huile', de: 'Ölfilter' }, commons: ['Oil filters'] },
  { key: 'cabin-filter', label: { pt: 'Filtros de habitáculo', es: 'Filtros de habitáculo', en: 'Cabin filters', fr: 'Filtres d’habitacle', de: 'Innenraumfilter', it: 'Filtri abitacolo' }, category: 'filtros', match: /habitaculo|polen/, search: 'cabin air filter', terms: { pt: 'filtro de habitáculo', es: 'filtro de habitáculo', fr: 'filtre d\'habitacle', de: 'Innenraumfilter' } },
  { key: 'fuel-filter', label: { pt: 'Filtros de combustível', es: 'Filtros de combustible', en: 'Fuel filters', fr: 'Filtres à carburant', de: 'Kraftstofffilter', it: 'Filtri carburante' }, category: 'filtros', match: /combustivel|gasoleo/, search: 'fuel filter', terms: { pt: 'filtro de combustível', es: 'filtro de combustible', fr: 'filtre à carburant', de: 'Kraftstofffilter' }, commons: ['Fuel filters'] },
  { key: 'air-filter', label: { pt: 'Filtros de ar', es: 'Filtros de aire', en: 'Air filters', fr: 'Filtres à air', de: 'Luftfilter', it: 'Filtri aria' }, category: 'filtros', match: /filtro de ar/, search: 'air filter element', terms: { pt: 'filtro de ar automóvel', es: 'filtro de aire coche', fr: 'filtre à air voiture', de: 'Luftfilter Auto' }, commons: ['Air filters'] },
  // iluminacao
  { key: 'headlight', label: { pt: 'Faróis', es: 'Faros', en: 'Headlights', fr: 'Phares', de: 'Scheinwerfer', it: 'Fari' }, category: 'iluminacao', match: /farol(?!im)|otica/, search: 'car headlight', terms: { pt: 'farol automóvel', es: 'faro delantero coche', fr: 'phare automobile', de: 'Scheinwerfer Auto' }, commons: ['Automobile headlamps'] },
  { key: 'tail-light', label: { pt: 'Farolins', es: 'Pilotos traseros', en: 'Tail lights', fr: 'Feux arrière', de: 'Rückleuchten', it: 'Fanali posteriori' }, category: 'iluminacao', match: /farolim/, search: 'car tail light', terms: { pt: 'farolim traseiro', es: 'piloto trasero coche', fr: 'feu arrière voiture', de: 'Rückleuchte' }, commons: ['Automobile tail lights', 'Automobile rear lights'] },
  { key: 'bulb', label: { pt: 'Lâmpadas', es: 'Bombillas', en: 'Bulbs', fr: 'Ampoules', de: 'Glühlampen', it: 'Lampadine' }, category: 'iluminacao', match: /lampada/, search: 'halogen headlight bulb', terms: { pt: 'lâmpada halogénea automóvel', es: 'bombilla halógena coche', fr: 'ampoule halogène voiture', de: 'Halogenlampe Auto' }, commons: ['Automobile light bulbs', 'H4 lamps'] },
  // suspensao
  { key: 'shock-absorber', label: { pt: 'Amortecedores', es: 'Amortiguadores', en: 'Shock absorbers', fr: 'Amortisseurs', de: 'Stoßdämpfer', it: 'Ammortizzatori' }, category: 'suspensao', match: /amortecedor/, search: 'shock absorber car part', terms: { pt: 'amortecedor automóvel', es: 'amortiguador coche', fr: 'amortisseur voiture', de: 'Stoßdämpfer Auto' }, commons: ['Automobile shock absorbers'] },
  { key: 'stabilizer-link', label: { pt: 'Bieletas', es: 'Bieletas', en: 'Stabilizer links', fr: 'Biellettes', de: 'Koppelstangen', it: 'Bielette' }, category: 'suspensao', match: /bieleta/, search: 'anti-roll bar link', terms: { pt: 'bieleta barra estabilizadora', es: 'bieleta estabilizadora', fr: 'biellette de barre stabilisatrice', de: 'Koppelstange' }, commons: ['Anti-roll bars'] },
  { key: 'control-arm', label: { pt: 'Braços de suspensão', es: 'Brazos de suspensión', en: 'Control arms', fr: 'Triangles de suspension', de: 'Querlenker', it: 'Bracci oscillanti' }, category: 'suspensao', match: /braco/, search: 'wishbone suspension', terms: { pt: 'braço de suspensão', es: 'brazo de suspensión', fr: 'triangle de suspension', de: 'Querlenker' }, commons: ['Control arms', 'Double wishbone suspension'] },
  { key: 'coil-spring', label: { pt: 'Molas de suspensão', es: 'Muelles de suspensión', en: 'Coil springs', fr: 'Ressorts de suspension', de: 'Fahrwerksfedern', it: 'Molle sospensione' }, category: 'suspensao', match: /mola/, search: 'coil spring suspension', terms: { pt: 'mola de suspensão', es: 'muelle de suspensión', fr: 'ressort de suspension', de: 'Schraubenfeder Fahrwerk' }, commons: ['Automobile springs', 'Coil springs'] },
  // direcao
  { key: 'power-steering-pump', label: { pt: 'Bombas de direção assistida', es: 'Bombas de dirección', en: 'Power steering pumps', fr: 'Pompes de direction', de: 'Servopumpen', it: 'Pompe servosterzo' }, category: 'direcao', match: /bomba/, search: 'power steering pump car', terms: { pt: 'bomba de direção assistida', es: 'bomba de dirección asistida', fr: 'pompe de direction assistée', de: 'Servopumpe' } },
  { key: 'ball-joint', label: { pt: 'Rótulas', es: 'Rótulas', en: 'Ball joints', fr: 'Rotules', de: 'Traggelenke', it: 'Giunti sferici' }, category: 'direcao', match: /rotula/, search: 'ball joint automotive', terms: { pt: 'rótula de suspensão', es: 'rótula de suspensión', fr: 'rotule de suspension', de: 'Traggelenk' }, commons: ['Ball joints'] },
  { key: 'tie-rod-end', label: { pt: 'Terminais de direção', es: 'Rótulas de dirección', en: 'Tie rod ends', fr: 'Rotules de direction', de: 'Spurstangenköpfe', it: 'Testine sterzo' }, category: 'direcao', match: /terminal/, search: 'tie rod end', terms: { pt: 'terminal de direção', es: 'rótula de dirección', fr: 'rotule de direction', de: 'Spurstangenkopf' }, commons: ['Tie rods'] },
  // transmissao
  { key: 'cv-joint', label: { pt: 'Juntas homocinéticas', es: 'Juntas homocinéticas', en: 'CV joints', fr: 'Joints homocinétiques', de: 'Gleichlaufgelenke', it: 'Giunti omocinetici' }, category: 'transmissao', match: /homocinetica/, search: 'constant velocity joint', terms: { pt: 'junta homocinética', es: 'junta homocinética', fr: 'joint homocinétique', de: 'Gleichlaufgelenk' }, commons: ['Constant-velocity joints'] },
  { key: 'wheel-bearing', label: { pt: 'Rolamentos de roda', es: 'Rodamientos de rueda', en: 'Wheel bearings', fr: 'Roulements de roue', de: 'Radlager', it: 'Cuscinetti ruota' }, category: 'transmissao', match: /rolamento/, search: 'wheel hub bearing', terms: { pt: 'rolamento de roda', es: 'rodamiento de rueda', fr: 'roulement de roue', de: 'Radlager' }, commons: ['Automobile wheel hubs', 'Wheel bearings'] },
  { key: 'drive-shaft', label: { pt: 'Semieixos', es: 'Palieres', en: 'Drive shafts', fr: 'Cardans', de: 'Antriebswellen', it: 'Semiassi' }, category: 'transmissao', match: /semieixo/, search: 'CV axle', terms: { pt: 'semieixo de transmissão', es: 'palier transmisión', fr: 'cardan de transmission', de: 'Antriebswelle' }, commons: ['Drive shafts', 'Automobile axles'] },
  // motor
  { key: 'water-pump', label: { pt: 'Bombas de água', es: 'Bombas de agua', en: 'Water pumps', fr: 'Pompes à eau', de: 'Wasserpumpen', it: 'Pompe acqua' }, category: 'motor', match: /bomba de agua/, search: 'water pump automobile', terms: { pt: 'bomba de água motor', es: 'bomba de agua motor', fr: 'pompe à eau moteur', de: 'Wasserpumpe Motor' }, commons: ['Water pumps (engine)'] },
  { key: 'accessory-belt', label: { pt: 'Correias de acessórios', es: 'Correas auxiliares', en: 'Accessory belts', fr: 'Courroies d’accessoires', de: 'Keilrippenriemen', it: 'Cinghie servizi' }, category: 'motor', match: /correia de acessorios/, search: 'V-ribbed belt', terms: { pt: 'correia de acessórios', es: 'correa poli-V', fr: 'courroie d\'accessoires', de: 'Keilrippenriemen' }, commons: ['Serpentine belts', 'V-belts'] },
  { key: 'valve-cover-gasket', label: { pt: 'Juntas da tampa das válvulas', es: 'Juntas de tapa de balancines', en: 'Valve cover gaskets', fr: 'Joints de cache-culbuteurs', de: 'Ventildeckeldichtungen', it: 'Guarnizioni coperchio valvole' }, category: 'motor', match: /junta/, search: 'cylinder head cover gasket', terms: { pt: 'junta da tampa das válvulas', es: 'junta tapa de balancines', fr: 'joint de cache-culbuteurs', de: 'Ventildeckeldichtung' } },
  { key: 'timing-kit', label: { pt: 'Kits de distribuição', es: 'Kits de distribución', en: 'Timing kits', fr: 'Kits de distribution', de: 'Zahnriemensätze', it: 'Kit distribuzione' }, category: 'motor', match: /distribuicao/, search: 'timing belt', terms: { pt: 'correia de distribuição', es: 'correa de distribución', fr: 'courroie de distribution', de: 'Zahnriemen' }, commons: ['Timing belts'] },
  // refrigeracao
  { key: 'thermostat', label: { pt: 'Termóstatos', es: 'Termostatos', en: 'Thermostats', fr: 'Thermostats', de: 'Thermostate', it: 'Termostati' }, category: 'refrigeracao', match: /termostato/, search: 'engine thermostat', terms: { pt: 'termóstato motor', es: 'termostato motor', fr: 'thermostat moteur', de: 'Thermostat Kühlsystem' }, commons: ['Thermostat housing'] },
  { key: 'radiator-fan', label: { pt: 'Ventiladores do radiador', es: 'Electroventiladores', en: 'Radiator fans', fr: 'Ventilateurs de radiateur', de: 'Kühlerlüfter', it: 'Elettroventole' }, category: 'refrigeracao', match: /ventilador/, search: 'radiator cooling fan', terms: { pt: 'ventilador do radiador', es: 'electroventilador', fr: 'ventilateur de radiateur', de: 'Kühlerlüfter' } },
  { key: 'radiator', label: { pt: 'Radiadores', es: 'Radiadores', en: 'Radiators', fr: 'Radiateurs', de: 'Kühler', it: 'Radiatori' }, category: 'refrigeracao', match: /radiador/, search: 'radiator automobile cooling', terms: { pt: 'radiador do motor', es: 'radiador coche', fr: 'radiateur moteur', de: 'Kühler Auto' }, similar: 'radiator-fan', commons: ['Automobile radiators'] },
  // eletrico
  { key: 'alternator', label: { pt: 'Alternadores', es: 'Alternadores', en: 'Alternators', fr: 'Alternateurs', de: 'Lichtmaschinen', it: 'Alternatori' }, category: 'eletrico', match: /alternador/, search: 'alternator', terms: { pt: 'alternador', es: 'alternador coche', fr: 'alternateur', de: 'Lichtmaschine' }, commons: ['Automobile alternators'] },
  { key: 'starter-motor', label: { pt: 'Motores de arranque', es: 'Motores de arranque', en: 'Starter motors', fr: 'Démarreurs', de: 'Anlasser', it: 'Motorini di avviamento' }, category: 'eletrico', match: /arranque/, search: 'starter motor', terms: { pt: 'motor de arranque', es: 'motor de arranque', fr: 'démarreur', de: 'Anlasser' }, commons: ['Engine starters', 'Electric starter motors'] },
  { key: 'battery', label: { pt: 'Baterias', es: 'Baterías', en: 'Batteries', fr: 'Batteries', de: 'Batterien', it: 'Batterie' }, category: 'eletrico', match: /bateria/, search: 'car battery', terms: { pt: 'bateria automóvel', es: 'batería coche', fr: 'batterie voiture', de: 'Autobatterie' }, commons: ['Automobile batteries'] },
  { key: 'abs-sensor', label: { pt: 'Sensores ABS', es: 'Sensores ABS', en: 'ABS sensors', fr: 'Capteurs ABS', de: 'ABS-Sensoren', it: 'Sensori ABS' }, category: 'eletrico', match: /abs/, search: 'ABS sensor', terms: { pt: 'sensor ABS', es: 'sensor ABS', fr: 'capteur ABS', de: 'ABS-Sensor' }, commons: ['Automobile sensors'] },
  // embraiagem
  { key: 'clutch-kit', label: { pt: 'Kits de embraiagem', es: 'Kits de embrague', en: 'Clutch kits', fr: 'Kits d’embrayage', de: 'Kupplungssätze', it: 'Kit frizione' }, category: 'embraiagem', match: /kit de embraiagem/, search: 'clutch disc', terms: { pt: 'kit de embraiagem', es: 'kit de embrague', fr: 'kit d\'embrayage', de: 'Kupplungssatz' }, commons: ['Automobile clutches', 'Clutch discs'] },
  { key: 'clutch-bearing', label: { pt: 'Rolamentos de embraiagem', es: 'Cojinetes de embrague', en: 'Clutch release bearings', fr: 'Butées d’embrayage', de: 'Ausrücklager', it: 'Cuscinetti reggispinta' }, category: 'embraiagem', match: /rolamento/, search: 'clutch release bearing', terms: { pt: 'rolamento de embraiagem', es: 'cojinete de embrague', fr: 'butée d\'embrayage', de: 'Ausrücklager' }, commons: ['Clutch release bearings'] },
  { key: 'flywheel', label: { pt: 'Volantes bimassa', es: 'Volantes bimasa', en: 'Dual-mass flywheels', fr: 'Volants bimasse', de: 'Zweimassenschwungräder', it: 'Volani bimassa' }, category: 'embraiagem', match: /volante/, search: 'dual mass flywheel', terms: { pt: 'volante bimassa', es: 'volante bimasa', fr: 'volant moteur bimasse', de: 'Zweimassenschwungrad' }, commons: ['Dual-mass flywheels', 'Flywheels'] },
  // escape
  { key: 'muffler', label: { pt: 'Silenciadores', es: 'Silenciadores', en: 'Mufflers', fr: 'Silencieux', de: 'Auspufftöpfe', it: 'Silenziatori' }, category: 'escape', match: /silenciador/, search: 'car muffler', terms: { pt: 'silenciador de escape', es: 'silenciador escape', fr: 'silencieux d\'échappement', de: 'Auspufftopf' }, commons: ['Mufflers', 'Automobile exhausts'] },
  { key: 'lambda-sensor', label: { pt: 'Sondas lambda', es: 'Sondas lambda', en: 'Lambda sensors', fr: 'Sondes lambda', de: 'Lambdasonden', it: 'Sonde lambda' }, category: 'escape', match: /lambda/, search: 'oxygen sensor lambda', terms: { pt: 'sonda lambda', es: 'sonda lambda', fr: 'sonde lambda', de: 'Lambdasonde' }, commons: ['Oxygen sensors'] },
  // ar-condicionado
  { key: 'ac-compressor', label: { pt: 'Compressores de ar condicionado', es: 'Compresores de aire acondicionado', en: 'A/C compressors', fr: 'Compresseurs de climatisation', de: 'Klimakompressoren', it: 'Compressori A/C' }, category: 'ar-condicionado', match: /compressor/, search: 'Klimakompressor', terms: { pt: 'compressor de ar condicionado', es: 'compresor aire acondicionado', fr: 'compresseur de climatisation', de: 'Klimakompressor' }, commons: ['Automobile air conditioning'] },
  { key: 'ac-condenser', label: { pt: 'Condensadores de ar condicionado', es: 'Condensadores de aire acondicionado', en: 'A/C condensers', fr: 'Condenseurs de climatisation', de: 'Klimakondensatoren', it: 'Condensatori A/C' }, category: 'ar-condicionado', match: /condensador/, search: 'Klimakondensator', terms: { pt: 'condensador ar condicionado', es: 'condensador aire acondicionado', fr: 'condenseur de climatisation', de: 'Klimakondensator' }, similar: 'ac-compressor' },
  // carrocaria
  { key: 'wiper-blades', label: { pt: 'Escovas limpa-vidros', es: 'Escobillas limpiaparabrisas', en: 'Wiper blades', fr: 'Balais d’essuie-glace', de: 'Scheibenwischer', it: 'Spazzole tergicristallo' }, category: 'carrocaria', match: /escova|limpa/, search: 'wiper blade', terms: { pt: 'escovas limpa-vidros', es: 'escobillas limpiaparabrisas', fr: 'balais d\'essuie-glace', de: 'Scheibenwischer' }, commons: ['Automobile windshield wipers'] },
  { key: 'bumper-grille', label: { pt: 'Grelhas', es: 'Rejillas', en: 'Grilles', fr: 'Grilles', de: 'Kühlergrills', it: 'Griglie' }, category: 'carrocaria', match: /grelha/, search: 'radiator grille', terms: { pt: 'grelha do para-choques', es: 'rejilla parachoques', fr: 'grille de pare-chocs', de: 'Kühlergrill' }, commons: ['Automobile grilles'] },
  { key: 'bumper', label: { pt: 'Para-choques', es: 'Parachoques', en: 'Bumpers', fr: 'Pare-chocs', de: 'Stoßstangen', it: 'Paraurti' }, category: 'carrocaria', match: /para-choques/, search: 'car bumper', terms: { pt: 'para-choques', es: 'parachoques', fr: 'pare-chocs', de: 'Stoßstange' }, commons: ['Bumpers'] },
  { key: 'side-mirror', label: { pt: 'Retrovisores', es: 'Retrovisores', en: 'Side mirrors', fr: 'Rétroviseurs', de: 'Außenspiegel', it: 'Specchietti retrovisori' }, category: 'carrocaria', match: /retrovisor/, search: 'car side mirror', terms: { pt: 'retrovisor exterior', es: 'retrovisor exterior', fr: 'rétroviseur extérieur', de: 'Außenspiegel' }, commons: ['Automobile mirrors', 'Wing mirrors'] },
  // acessorios
  { key: 'roof-bars', label: { pt: 'Barras de tejadilho', es: 'Barras de techo', en: 'Roof bars', fr: 'Barres de toit', de: 'Dachträger', it: 'Barre portatutto' }, category: 'acessorios', match: /tejadilho/, search: 'roof rack bars car', terms: { pt: 'barras de tejadilho', es: 'barras de techo', fr: 'barres de toit', de: 'Dachträger' }, commons: ['Roof racks'] },
  { key: 'floor-mats', label: { pt: 'Tapetes', es: 'Alfombrillas', en: 'Floor mats', fr: 'Tapis de sol', de: 'Fußmatten', it: 'Tappetini' }, category: 'acessorios', match: /tapete/, search: 'car floor mats', terms: { pt: 'tapetes de borracha automóvel', es: 'alfombrillas de goma coche', fr: 'tapis de sol voiture', de: 'Gummifußmatten' } },
  { key: 'first-aid-kit', label: { pt: 'Kits de primeiros socorros', es: 'Botiquines', en: 'First aid kits', fr: 'Trousses de secours', de: 'Verbandkästen', it: 'Kit di pronto soccorso' }, category: 'acessorios', match: /socorros/, search: 'first aid kit', terms: { pt: 'kit de primeiros socorros', es: 'botiquín coche', fr: 'trousse de secours', de: 'Verbandkasten' }, commons: ['First aid kits'] },
  { key: 'warning-triangle', label: { pt: 'Triângulos de sinalização', es: 'Triángulos de emergencia', en: 'Warning triangles', fr: 'Triangles de signalisation', de: 'Warndreiecke', it: 'Triangoli di emergenza' }, category: 'acessorios', match: /triangulo/, search: 'warning triangle', terms: { pt: 'triângulo de sinalização', es: 'triángulo de emergencia', fr: 'triangle de signalisation', de: 'Warndreieck' }, commons: ['Warning triangles'] },
  // consumiveis
  { key: 'coolant', label: { pt: 'Líquido de refrigeração', es: 'Anticongelante', en: 'Coolant', fr: 'Liquide de refroidissement', de: 'Kühlmittel', it: 'Liquido refrigerante' }, category: 'consumiveis', match: /refrigeracao/, search: 'antifreeze coolant', terms: { pt: 'líquido de refrigeração', es: 'anticongelante coche', fr: 'liquide de refroidissement', de: 'Kühlerfrostschutz' } },
  { key: 'brake-fluid', label: { pt: 'Líquido de travões', es: 'Líquido de frenos', en: 'Brake fluid', fr: 'Liquide de frein', de: 'Bremsflüssigkeit', it: 'Liquido freni' }, category: 'consumiveis', match: /travoes/, search: 'brake fluid', terms: { pt: 'líquido de travões', es: 'líquido de frenos', fr: 'liquide de frein', de: 'Bremsflüssigkeit' } },
  { key: 'washer-fluid', label: { pt: 'Líquido limpa-vidros', es: 'Líquido limpiaparabrisas', en: 'Washer fluid', fr: 'Lave-glace', de: 'Scheibenreiniger', it: 'Liquido lavavetri' }, category: 'consumiveis', match: /limpa-vidros/, search: 'windshield washer fluid', terms: { pt: 'líquido limpa-vidros', es: 'líquido limpiaparabrisas', fr: 'lave-glace', de: 'Scheibenwaschwasser' } },
  { key: 'engine-oil', label: { pt: 'Óleo de motor', es: 'Aceite de motor', en: 'Engine oil', fr: 'Huile moteur', de: 'Motoröl', it: 'Olio motore' }, category: 'consumiveis', match: /oleo/, search: 'motor oil', terms: { pt: 'óleo de motor', es: 'aceite de motor', fr: 'huile moteur', de: 'Motoröl' } },
  // Part types without products yet (for future supplier catalogues and the categories page)
  { key: 'brake-drum', label: { pt: 'Tambores de travão', es: 'Tambores de freno', en: 'Brake drums', fr: 'Tambours de frein', de: 'Bremstrommeln', it: 'Tamburi freno' }, category: 'travagem', match: /tambor/, search: 'brake drum', terms: { pt: 'tambor de travão', es: 'tambor de freno', fr: 'tambour de frein', de: 'Bremstrommel' }, commons: ['Automobile drum brakes'] },
  { key: 'brake-master-cylinder', label: { pt: 'Bombas de travão', es: 'Bombas de freno', en: 'Brake master cylinders', fr: 'Maîtres-cylindres de frein', de: 'Hauptbremszylinder', it: 'Pompe freno' }, category: 'travagem', match: /bomba de travao|cilindro mestre|servofreio/, search: 'brake master cylinder', terms: { pt: 'bomba de travão', es: 'bomba de freno', fr: 'maître-cylindre de frein', de: 'Hauptbremszylinder' }, commons: ['Brake master cylinders', 'Vacuum servos'] },
  { key: 'brake-hose', label: { pt: 'Tubos de travão', es: 'Latiguillos de freno', en: 'Brake hoses', fr: 'Flexibles de frein', de: 'Bremsschläuche', it: 'Tubi freno' }, category: 'travagem', match: /tubo|flexivel/, search: 'brake hose', terms: { pt: 'tubo de travão', es: 'latiguillo de freno', fr: 'flexible de frein', de: 'Bremsschlauch' }, commons: ['Brake hoses', 'Brake lines'] },
  { key: 'glow-plug', label: { pt: 'Velas de incandescência', es: 'Bujías de precalentamiento', en: 'Glow plugs', fr: 'Bougies de préchauffage', de: 'Glühkerzen', it: 'Candelette' }, category: 'motor', match: /incandescencia/, search: 'glow plug', terms: { pt: 'vela de incandescência', es: 'bujía de precalentamiento', fr: 'bougie de préchauffage', de: 'Glühkerze' }, commons: ['Glow plugs'] },
  { key: 'spark-plug', label: { pt: 'Velas de ignição', es: 'Bujías', en: 'Spark plugs', fr: 'Bougies d’allumage', de: 'Zündkerzen', it: 'Candele' }, category: 'motor', match: /vela/, search: 'spark plug', terms: { pt: 'vela de ignição', es: 'bujía', fr: 'bougie d\'allumage', de: 'Zündkerze' }, commons: ['Spark plugs'] },
  { key: 'turbocharger', label: { pt: 'Turbocompressores', es: 'Turbocompresores', en: 'Turbochargers', fr: 'Turbocompresseurs', de: 'Turbolader', it: 'Turbocompressori' }, category: 'motor', match: /turbo/, search: 'turbocharger', terms: { pt: 'turbocompressor', es: 'turbocompresor', fr: 'turbocompresseur', de: 'Turbolader' }, commons: ['Turbochargers'] },
  { key: 'fuel-injector', label: { pt: 'Injetores', es: 'Inyectores', en: 'Fuel injectors', fr: 'Injecteurs', de: 'Einspritzdüsen', it: 'Iniettori' }, category: 'motor', match: /injetor|injector/, search: 'fuel injector', terms: { pt: 'injetor de combustível', es: 'inyector de combustible', fr: 'injecteur', de: 'Einspritzdüse' }, commons: ['Fuel injectors'] },
  { key: 'pulley', label: { pt: 'Polias', es: 'Poleas', en: 'Pulleys', fr: 'Poulies', de: 'Riemenscheiben', it: 'Pulegge' }, category: 'motor', match: /polia/, search: 'crankshaft pulley', terms: { pt: 'polia da cambota', es: 'polea del cigüeñal', fr: 'poulie de vilebrequin', de: 'Riemenscheibe Kurbelwelle' }, commons: ['Pulleys'] },
  { key: 'ignition-coil', label: { pt: 'Bobinas de ignição', es: 'Bobinas de encendido', en: 'Ignition coils', fr: 'Bobines d’allumage', de: 'Zündspulen', it: 'Bobine di accensione' }, category: 'eletrico', match: /bobina/, search: 'ignition coil', terms: { pt: 'bobina de ignição', es: 'bobina de encendido', fr: 'bobine d\'allumage', de: 'Zündspule' }, commons: ['Ignition coils'] },
  { key: 'fuse', label: { pt: 'Fusíveis', es: 'Fusibles', en: 'Fuses', fr: 'Fusibles', de: 'Sicherungen', it: 'Fusibili' }, category: 'eletrico', match: /fusivel/, search: 'automotive blade fuse', terms: { pt: 'fusível automóvel', es: 'fusible de coche', fr: 'fusible automobile', de: 'Kfz-Sicherung' }, commons: ['Automobile fuses'] },
  { key: 'relay', label: { pt: 'Relés', es: 'Relés', en: 'Relays', fr: 'Relais', de: 'Relais', it: 'Relè' }, category: 'eletrico', match: /rele/, search: 'automotive relay', terms: { pt: 'relé automóvel', es: 'relé de coche', fr: 'relais automobile', de: 'Kfz-Relais' }, commons: ['Automobile relays'] },
  { key: 'horn', label: { pt: 'Buzinas', es: 'Cláxones', en: 'Horns', fr: 'Avertisseurs sonores', de: 'Hupen', it: 'Clacson' }, category: 'eletrico', match: /buzina/, search: 'car horn', terms: { pt: 'buzina automóvel', es: 'claxon coche', fr: 'klaxon voiture', de: 'Autohupe' }, commons: ['Automobile horns'] },
  { key: 'gearbox', label: { pt: 'Caixas de velocidades', es: 'Cajas de cambios', en: 'Gearboxes', fr: 'Boîtes de vitesses', de: 'Getriebe', it: 'Cambi' }, category: 'transmissao', match: /caixa de velocidades/, search: 'manual gearbox car', terms: { pt: 'caixa de velocidades', es: 'caja de cambios', fr: 'boîte de vitesses', de: 'Schaltgetriebe' }, commons: ['Automotive manual transmissions'] },
  { key: 'differential', label: { pt: 'Diferenciais', es: 'Diferenciales', en: 'Differentials', fr: 'Différentiels', de: 'Differentiale', it: 'Differenziali' }, category: 'transmissao', match: /diferencial/, search: 'differential gear car', terms: { pt: 'diferencial automóvel', es: 'diferencial de coche', fr: 'différentiel automobile', de: 'Differentialgetriebe' }, commons: ['Differentials'] },
  { key: 'catalytic-converter', label: { pt: 'Catalisadores', es: 'Catalizadores', en: 'Catalytic converters', fr: 'Catalyseurs', de: 'Katalysatoren', it: 'Catalizzatori' }, category: 'escape', match: /catalisador/, search: 'catalytic converter', terms: { pt: 'catalisador automóvel', es: 'catalizador de coche', fr: 'pot catalytique', de: 'Katalysator Auto' }, commons: ['Catalytic converters'] },
  { key: 'fender', label: { pt: 'Guarda-lamas', es: 'Aletas', en: 'Fenders', fr: 'Ailes', de: 'Kotflügel', it: 'Parafanghi' }, category: 'carrocaria', match: /guarda-lamas/, search: 'car fender', terms: { pt: 'guarda-lamas automóvel', es: 'aleta de coche', fr: 'aile de voiture', de: 'Kotflügel' }, commons: ['Automobile fenders'] },
  { key: 'bonnet', label: { pt: 'Capôs', es: 'Capós', en: 'Bonnets', fr: 'Capots', de: 'Motorhauben', it: 'Cofani' }, category: 'carrocaria', match: /capo/, search: 'car hood bonnet', terms: { pt: 'capô automóvel', es: 'capó de coche', fr: 'capot de voiture', de: 'Motorhaube' }, commons: ['Automobile hoods'] },
  { key: 'door-handle', label: { pt: 'Puxadores de porta', es: 'Manillas de puerta', en: 'Door handles', fr: 'Poignées de porte', de: 'Türgriffe', it: 'Maniglie' }, category: 'carrocaria', match: /puxador|macaneta/, search: 'car door handle', terms: { pt: 'puxador de porta automóvel', es: 'manilla de puerta coche', fr: 'poignée de porte voiture', de: 'Türgriff Auto' }, commons: ['Automobile door handles'] },
  { key: 'door', label: { pt: 'Portas', es: 'Puertas', en: 'Doors', fr: 'Portières', de: 'Türen', it: 'Portiere' }, category: 'carrocaria', match: /porta/, search: 'car door', terms: { pt: 'porta de automóvel', es: 'puerta de coche', fr: 'portière de voiture', de: 'Autotür' }, commons: ['Automobile doors'] },
  { key: 'tyre', label: { pt: 'Pneus', es: 'Neumáticos', en: 'Tyres', fr: 'Pneus', de: 'Reifen', it: 'Pneumatici' }, category: 'acessorios', match: /pneu/, search: 'car tyre', terms: { pt: 'pneu automóvel', es: 'neumático de coche', fr: 'pneu de voiture', de: 'Autoreifen' }, commons: ['Automobile tire treads', 'Snow tires'] },
  { key: 'wheel-rim', label: { pt: 'Jantes', es: 'Llantas', en: 'Wheels', fr: 'Jantes', de: 'Felgen', it: 'Cerchi' }, category: 'acessorios', match: /jante/, search: 'alloy wheel', terms: { pt: 'jante de liga leve', es: 'llanta de aleación', fr: 'jante en alliage', de: 'Leichtmetallfelge' }, commons: ['Alloy wheels', 'Automobile steel wheels'] },
  { key: 'steering-wheel', label: { pt: 'Volantes de direção', es: 'Volantes', en: 'Steering wheels', fr: 'Volants', de: 'Lenkräder', it: 'Volanti' }, category: 'direcao', match: /volante/, search: 'car steering wheel', terms: { pt: 'volante de automóvel', es: 'volante de coche', fr: 'volant de voiture', de: 'Lenkrad' }, commons: ['Steering wheels'] },
  { key: 'expansion-tank', label: { pt: 'Vasos de expansão', es: 'Vasos de expansión', en: 'Expansion tanks', fr: 'Vases d’expansion', de: 'Ausgleichsbehälter', it: 'Vaschette di espansione' }, category: 'refrigeracao', match: /vaso de expansao|deposito de expansao/, search: 'coolant expansion tank', terms: { pt: 'vaso de expansão', es: 'vaso de expansión', fr: 'vase d\'expansion', de: 'Ausgleichsbehälter' }, commons: ['Coolant expansion tanks'] },
]

function plain(value: string): string {
  return value.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase()
}

/** The part type of a product, or null when no rule recognises it. */
export function partTypeOf(categorySlug: string | null | undefined, name: string): PartType | null {
  if (!categorySlug) return null
  const text = plain(name)
  return PART_TYPES.find((type) => type.category === categorySlug && type.match.test(text)) ?? null
}
